# You need to run:
# $ mkdir -p data mnt
# $ chown -R 65534:65534 data mnt
# at the first start to create directories with correct permissions

services:
  zipfs:
    # build: .
    image: ghcr.io/wvffle/fuse-zipfs@sha256:26f2bd358256cefe435f68fb333dd22917a10b208463a382b9ac2f27b64cacf8
    privileged: true
    volumes:
      - # Data/source directory
        source: ./data
        target: /app/data
        type: bind
      - # Mountpoint/target directory
        source: ./mnt
        target: /app/mnt
        type: bind
        bind:
          propagation: rshared
    environment:
      RUST_LOG: zipfs=debug
    command:
      - /app/data
      - /app/mnt
      - -o
      - allow_other
