# You need to run:
# $ mkdir -p data mnt
# $ chown -R 65534:65534 data mnt
# at the first start to create directories with correct permissions

services:
  zipfs:
    # build: .
    image: ghcr.io/wvffle/fuse-zipfs@sha256:cdc45a97161d7c71eeea68a4e9e43a12110ab106a708aa7fede78b6e49c8ffb7
    privileged: true
    volumes:
      - # Data/source directory
        source: ./data
        target: /app/data
        type: bind
      - # Mountpoint/target directory
        source: ./mnt
        target: /app/mnt
        type: bind
        bind:
          propagation: rshared
    environment:
      RUST_LOG: zipfs=debug
    command:
      - /app/data
      - /app/mnt
      - -o
      - allow_other
